"""Add teachers table

Revision ID: 915656c992bc
Revises: d6c3b32b07c1
Create Date: 2025-03-23 21:36:37.983318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '915656c992bc'
down_revision: Union[str, None] = 'd6c3b32b07c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('blood_group', sa.String(), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=False),
    sa.Column('aadhar_number', sa.String(), nullable=False),
    sa.Column('religion', sa.String(), nullable=False),
    sa.Column('caste', sa.String(), nullable=False),
    sa.Column('rci_number', sa.String(), nullable=False),
    sa.Column('rci_renewal_date', sa.Date(), nullable=False),
    sa.Column('qualifications_details', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadhar_number'),
    sa.UniqueConstraint('rci_number')
    )
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teachers_id'), table_name='teachers')
    op.drop_table('teachers')
    # ### end Alembic commands ###
